[package]
name = "synaptic-models"
description = "ProviderBackend abstraction and ChatModel wrappers (Retry, RateLimit, StructuredOutput, BoundTools)"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []
anthropic = []
gemini = []
ollama = []
bedrock = ["dep:aws-config", "dep:aws-sdk-bedrockruntime", "dep:aws-smithy-types"]
cohere = []
openai = ["dep:eventsource-stream"]

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
async-stream.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
synaptic-core = { version = "0.4", path = "../synaptic-core" }
tracing.workspace = true
eventsource-stream = { workspace = true, optional = true }

# bedrock
aws-config = { version = "1", optional = true }
aws-sdk-bedrockruntime = { version = "1", optional = true }
aws-smithy-types = { version = "1", optional = true }

[dev-dependencies]
tokio.workspace = true
futures.workspace = true
