[package]
name = "synaptic-events"
version.workspace = true
edition.workspace = true

[features]
default = []
otel = ["dep:opentelemetry"]

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync", "net", "io-util", "rt"] }
tracing = "0.1"
thiserror = "2"
futures = "0.3"
synaptic-core = { version = "0.4", path = "../synaptic-core" }

# otel
opentelemetry = { version = "0.28", optional = true }
